# Generated by Django 4.1.1 on 2022-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload',
            field=models.FileField(upload_to='./media/'),
        ),
    ]
