# Generated by Django 4.1.1 on 2022-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_rename_upload_mymodel_upload_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload_csv',
            field=models.FileField(upload_to='./'),
        ),
    ]
